version: "3.3"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: mentorme  
    volumes:
     - ./data:/docker-entrypoint-initdb.d
  backend:
    build: Server
    depends_on:
      - mysql
    environment:
      DBHOST: localhost
      DBUSERNAME: root
      DBPASSWORD: Root@123
      DBNAME: mentorme
    ports:
      - "3001:3001"
    restart: always   
  frontend:
    build: Frontend/student
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build: .
    ports:
      - "80:80"
    restart: always